# Generated by Django 5.0.4 on 2024-04-28 17:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vm", "0002_remove_vendor_average_response_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalperformance",
            name="average_response_time",
            field=models.FloatField(
                default=0,
                help_text="Historical average response time of the vendor for POs",
            ),
        ),
        migrations.AlterField(
            model_name="historicalperformance",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date when the performance data was recorded",
            ),
        ),
        migrations.AlterField(
            model_name="historicalperformance",
            name="fulfillment_rate",
            field=models.FloatField(
                default=0, help_text="Historical fulfillment rate of the vendor"
            ),
        ),
        migrations.AlterField(
            model_name="historicalperformance",
            name="on_time_delivery_rate",
            field=models.FloatField(
                default=0, help_text="Historical on-time delivery rate of the vendor"
            ),
        ),
        migrations.AlterField(
            model_name="historicalperformance",
            name="quality_rating_avg",
            field=models.FloatField(
                default=0, help_text="Historical average quality rating of the vendor"
            ),
        ),
        migrations.AlterField(
            model_name="historicalperformance",
            name="vendor",
            field=models.ForeignKey(
                help_text="Vendor associated with the performance data",
                on_delete=django.db.models.deletion.CASCADE,
                to="vm.vendor",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="acknowledgment_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when the PO was acknowledged by the vendor",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="delivery_date",
            field=models.DateTimeField(
                db_index=True, help_text="Expected delivery date of the PO"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="issue_date",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Date when the PO was issued",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="items",
            field=models.JSONField(help_text="Items included in the PO"),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_date",
            field=models.DateTimeField(
                db_index=True, help_text="Date when the PO was ordered"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="po_number",
            field=models.CharField(
                help_text="Unique identifier for the PO", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="quality_rating",
            field=models.FloatField(
                blank=True,
                help_text="Quality rating of the PO (if available)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="quantity",
            field=models.IntegerField(help_text="Quantity of items in the PO"),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("completed", "Completed"),
                    ("acknowledged", "Acknowledged"),
                ],
                db_index=True,
                default="draft",
                help_text="Status of the PO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="vendor",
            field=models.ForeignKey(
                help_text="Vendor associated with the PO",
                on_delete=django.db.models.deletion.CASCADE,
                to="vm.vendor",
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="address",
            field=models.TextField(help_text="Address of the vendor"),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="contact_details",
            field=models.TextField(help_text="Contact details of the vendor"),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="name",
            field=models.CharField(help_text="Name of the vendor", max_length=100),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="vendor_code",
            field=models.CharField(
                help_text="Unique code for the vendor", max_length=50, unique=True
            ),
        ),
    ]
